//
//  SAMConstants.m
//  ScheduleAlarmManagerBeta
//
//  Created by Eyong Nsoesie on 11/22/14.
//  Copyright (c) 2014 Scalior. All rights reserved.
//

#import "SCLRSAMConstants.h"

// AlarmProcessingUtil constants
const int ALARMPROCESSINGUTIL_SECOND_MS		= 1000;
const int ALARMPROCESSINGUTIL_MINUTE_MS		= 60 * ALARMPROCESSINGUTIL_SECOND_MS;
const int ALARMPROCESSINGUTIL_HOUR_MS		= 60 * ALARMPROCESSINGUTIL_MINUTE_MS;
const int ALARMPROCESSINGUTIL_DAY_MS		= 24 * ALARMPROCESSINGUTIL_HOUR_MS;
const int ALARMPROCESSINGUTIL_WEEK_MS		=  7 * ALARMPROCESSINGUTIL_DAY_MS;

const int ALARMPROCESSINGUTIL_SECOND_S		= 1;
const int ALARMPROCESSINGUTIL_MINUTE_S		= 60 * ALARMPROCESSINGUTIL_SECOND_S;
const int ALARMPROCESSINGUTIL_HOUR_S		= 60 * ALARMPROCESSINGUTIL_MINUTE_S;
const int ALARMPROCESSINGUTIL_DAY_S			= 24 * ALARMPROCESSINGUTIL_HOUR_S;
const int ALARMPROCESSINGUTIL_WEEK_S		=  7 * ALARMPROCESSINGUTIL_DAY_S;

// MONTH and YEAR constants are inaccurate.
const int ALARMPROCESSINGUTIL_MONTH_S		= 30 * ALARMPROCESSINGUTIL_DAY_S;
const int ALARMPROCESSINGUTIL_YEAR_S		= 365 * ALARMPROCESSINGUTIL_DAY_S;

/* / RepeatType constants
const int REPEAT_TYPE_HOURLY		= 1;
const int REPEAT_TYPE_DAILY			= 2;
const int REPEAT_TYPE_WEEKLY		= 3;
const int REPEAT_TYPE_MONTHLY		= 4;
const int REPEAT_TYPE_YEARLY		= 5;
const int REPEAT_TYPE_NONE			= 6;
*/

// Schedule state constants
NSString * const SCHEDULE_STATE_ON		= @"ON";
NSString * const SCHEDULE_STATE_OFF		= @"OFF";
